#!/usr/bin/env python3
"""Generate test/obj_input.inc: a 4-frame 16x16 4bpp sprite in OBJ tile order.

The OBJ-order sibling of gen-test-sprite.py's linear diamond-pulse: same
geometry (pulsing diamond + corner marker dot identifying the frame), but
emitted VRAM-ready for direct copy into OBJ character memory (1D mapping,
4 tiles per frame). Feeds carts that exercise the OAM path.

Usage: python tools/gen-test-obj.py > test/obj_input.inc
"""

W = H = 16
FRAMES = 4


def bgr555(r, g, b):
    return r | (g << 5) | (b << 10)


PAL = [
    0x0000,               # 0 transparent
    bgr555(10, 4, 4),     # 1 outline: dark red-brown
    bgr555(28, 16, 4),    # 2 fill: amber
    bgr555(31, 30, 22),   # 3 center: cream
    bgr555(4, 24, 28),    # 4 marker dot: cyan
    0x0000, 0x0000, 0x0000,  # 5..7 unused
]

RADII = [3, 5, 7, 5]                          # per-frame diamond radius
DOTS = [(12, 3), (12, 12), (3, 12), (3, 3)]   # per-frame 2x2 marker corner


def pixel(f, x, y):
    d2 = abs(2 * x - 15) + abs(2 * y - 15)
    r2 = 2 * RADII[f]
    dx, dy = DOTS[f]
    if dx <= x <= dx + 1 and dy <= y <= dy + 1:
        return 4
    if d2 <= 3:
        return 3
    if d2 <= r2 - 2:
        return 2
    if d2 <= r2:
        return 1
    return 0


def tile_bytes():
    """OBJ 8x8-tile order: 4 tiles per 16x16 frame, row-major within a tile."""
    out = []
    for f in range(FRAMES):
        for ty in range(2):
            for tx in range(2):
                for y in range(8):
                    for x in range(0, 8, 2):
                        lo = pixel(f, tx * 8 + x, ty * 8 + y)
                        hi = pixel(f, tx * 8 + x + 1, ty * 8 + y)
                        out.append(lo | (hi << 4))
    return out


def main():
    data = tile_bytes()
    assert len(data) == FRAMES * W * H // 2
    print("{ %d frames, %dx%d, 4bpp, GBA OBJ tile order (VRAM-ready, 1D mapping);" % (FRAMES, W, H))
    print("  geometric diamond-pulse test pattern generated by tools/gen-test-obj.py }")
    print("const OBJPULSE_W = %d;" % W)
    print("  OBJPULSE_H = %d;" % H)
    print("  OBJPULSE_FRAMES = %d;" % FRAMES)
    print("  OBJPULSE_OBJ_ORDER = 1;")
    pal = ", ".join("$%04X" % v for v in PAL)
    print("  OBJPULSE_PAL: array[0..%d] of Word = (" % (len(PAL) - 1))
    print("    %s);" % pal)
    print("  OBJPULSE_TILES: array[0..%d] of Byte = (" % (len(data) - 1))
    for i in range(0, len(data), 16):
        row = ", ".join("$%02X" % b for b in data[i:i + 16])
        sep = ");" if i + 16 >= len(data) else ","
        print("    %s%s" % (row, sep))


if __name__ == "__main__":
    main()
