#!/usr/bin/env python3
"""Generate test/sprite_input.inc: a 4-frame 16x16 4bpp diamond-pulse test sprite.

The pattern is pure geometry (no external art): a diamond that pulses through
radii 3/5/7/5 with a 2x2 marker dot that moves to a different corner each frame,
so single-frame screenshots identify which frame rendered. Data is emitted in
linear scanline order (SPRITE_OBJ_ORDER = 0); the sprite_smoke harness transposes
to GBA tile order itself.

Usage: python gen-test-sprite.py > sprite_input.inc
"""

W = H = 16
FRAMES = 4


def bgr555(r, g, b):
    return r | (g << 5) | (b << 10)


# Palette bank 0: index 0 transparent, then outline / fill / center / marker.
PAL = [
    0x0000,               # 0 transparent
    bgr555(4, 6, 10),     # 1 outline: dark slate blue
    bgr555(6, 20, 18),    # 2 fill: teal
    bgr555(28, 30, 20),   # 3 center: pale yellow
    bgr555(30, 12, 4),    # 4 marker dot: orange
    0x0000, 0x0000, 0x0000,  # 5..7 unused
]

RADII = [3, 5, 7, 5]                      # per-frame diamond radius
DOTS = [(12, 3), (12, 12), (3, 12), (3, 3)]  # per-frame 2x2 marker corner


def pixel(f, x, y):
    # Doubled Manhattan distance from the tile center (7.5, 7.5).
    d2 = abs(2 * x - 15) + abs(2 * y - 15)
    r2 = 2 * RADII[f]
    dx, dy = DOTS[f]
    if dx <= x <= dx + 1 and dy <= y <= dy + 1:
        return 4
    if d2 <= 3:
        return 3
    if d2 <= r2 - 2:
        return 2
    if d2 <= r2:
        return 1
    return 0


def tile_bytes():
    out = []
    for f in range(FRAMES):
        for y in range(H):
            for x in range(0, W, 2):
                lo = pixel(f, x, y)
                hi = pixel(f, x + 1, y)
                out.append(lo | (hi << 4))
    return out


def main():
    data = tile_bytes()
    assert len(data) == FRAMES * W * H // 2
    print("{ %d frames, %dx%d, 4bpp, linear scanline order; geometric diamond-pulse" % (FRAMES, W, H))
    print("  test pattern generated by tools/gen-test-sprite.py }")
    print("const SPRITE_W = %d;" % W)
    print("  SPRITE_H = %d;" % H)
    print("  SPRITE_FRAMES = %d;" % FRAMES)
    print("  SPRITE_OBJ_ORDER = 0;")
    pal = ", ".join("$%04X" % v for v in PAL)
    print("  SPRITE_PAL: array[0..%d] of Word = (" % (len(PAL) - 1))
    print("    %s);" % pal)
    print("  SPRITE_TILES: array[0..%d] of Byte = (" % (len(data) - 1))
    for i in range(0, len(data), 16):
        row = ", ".join("$%02X" % b for b in data[i:i + 16])
        sep = ");" if i + 16 >= len(data) else ","
        print("    %s%s" % (row, sep))


if __name__ == "__main__":
    main()
