# Run after devkitPro installer finishes. Verifies the install +
# configures FPC's arm-gba target to use devkitARM's real libsysbase
# / libgba instead of our stub.

$ErrorActionPreference = 'Continue'

# 1. Locate devkitPro install
$devkitpro = $env:DEVKITPRO
if (-not $devkitpro -or -not (Test-Path $devkitpro)) {
  $devkitpro = 'C:\devkitPro'
}
Write-Host "DEVKITPRO: $devkitpro"

if (-not (Test-Path $devkitpro)) {
  Write-Host "devkitPro NOT installed at $devkitpro. Run install-devkitpro.ps1 first."
  exit 1
}

# 2. Verify expected files
$expected = @{
  'devkitARM binutils' = "$devkitpro\devkitARM\bin\arm-none-eabi-as.exe"
  'newlib libsysbase'  = "$devkitpro\devkitARM\arm-none-eabi\lib\libsysbase.a"
  'newlib libc'        = "$devkitpro\devkitARM\arm-none-eabi\lib\libc.a"
  'libgba'             = "$devkitpro\libgba\lib\libgba.a"
  'gbafix tool'        = "$devkitpro\tools\bin\gbafix.exe"
}

$ok = $true
foreach ($name in $expected.Keys) {
  $p = $expected[$name]
  if (Test-Path $p) {
    Write-Host "  OK : $name ($p)"
  } else {
    Write-Host "  -  : $name  MISSING ($p)"
    $ok = $false
  }
}

if (-not $ok) {
  Write-Host ''
  Write-Host 'Install incomplete. In the devkitPro installer GUI, make sure'
  Write-Host '"devkitARM" AND "GBA Development" components were ticked.'
  exit 1
}

# 3. Remove our stub libsysbase.a so devkitARM's real one wins
$stubLib = 'C:\fpcupdeluxe\fpc\units\arm-gba\libsysbase.a'
if (Test-Path $stubLib) {
  $stubSize = (Get-Item $stubLib).Length
  if ($stubSize -lt 10000) {
    # Our stub is < 10KB; real libsysbase from newlib is > 100KB.
    # Safe to delete by size check.
    Write-Host ''
    Write-Host "Removing stub libsysbase.a at $stubLib ($stubSize bytes)"
    Remove-Item $stubLib -Force
  } else {
    Write-Host "Keeping existing libsysbase.a at $stubLib ($stubSize bytes -- looks like real one already)"
  }
}

# 4. Build an fpc.cfg snippet that tells FPC to find devkitARM libs.
#    This is sourced by build-gba.ps1 via -@ option.
$cfgPath = Join-Path $PSScriptRoot 'fpc-gba.cfg'
$cfgBody = @"
# Auto-generated by verify-devkitpro.ps1 -- points FPC -Tgba at
# devkitARM's binutils + lib search paths so the link finds the
# real libsysbase.a, libc.a, libgba.a, libgcc.a.

#IFDEF FPC_CROSSCOMPILING
-FD$devkitpro\devkitARM\bin
-Fl$devkitpro\devkitARM\arm-none-eabi\lib
-Fl$devkitpro\libgba\lib
#ENDIF
"@
# Write as UTF-8 WITHOUT BOM. PS 5.x Set-Content -Encoding UTF8 writes
# a BOM, which FPC's @-include then chokes on. Bypass via .NET API.
[System.IO.File]::WriteAllText($cfgPath, $cfgBody, [System.Text.UTF8Encoding]::new($false))
Write-Host ''
Write-Host "Wrote FPC config snippet: $cfgPath"
Write-Host '(build-gba.ps1 will source this via -@)'

Write-Host ''
Write-Host '=== devkitPro install verified ==='
Write-Host 'You can now build Pascal-GBA programs with full Format() / heap support.'
Write-Host 'Try: .\build-gba.ps1 test\dbg_smoke'
