#!/usr/bin/env python3
"""WAV -> signed 8-bit PCM Pascal include for Kit_Audio.SamplePlay.

Reads a mono (or first-channel) PCM WAV, resamples to a GBA-friendly
rate (default 16384 Hz), converts to signed 8-bit, pads to a 4-byte
boundary (DMA FIFO transfers are 4 words of 4 bytes), and emits a
Pascal include:

    const SampleNameRate = 16384;
          SampleNameLen  = N;
          SampleNameData: array[0..N-1] of ShortInt = (...);

Usage:
    python tools/voice.py in.wav -o out.inc [--name stem] [--rate 16384]

The output is intended for DirectSound FIFO A playback via
Kit_Audio.SamplePlay(@SampleNameData[0], SampleNameLen, SampleNameRate).
"""

from __future__ import annotations

import argparse
import math
import struct
import sys
import wave
from pathlib import Path


def read_wav(path: Path):
    with wave.open(str(path), "rb") as w:
        ch = w.getnchannels()
        sw = w.getsampwidth()
        rate = w.getframerate()
        n = w.getnframes()
        raw = w.readframes(n)
    if sw == 1:
        # unsigned 8-bit WAV
        samples = [struct.unpack_from("B", raw, i)[0] - 128 for i in range(n * ch)]
    elif sw == 2:
        samples = list(struct.unpack_from(f"<{n * ch}h", raw))
    else:
        raise SystemExit(f"unsupported sample width {sw}")
    if ch > 1:
        # take left channel only
        samples = samples[0::ch]
    return rate, samples


def resample(samples, src_rate: int, dst_rate: int):
    if src_rate == dst_rate:
        return samples
    if not samples:
        return samples
    out_len = max(1, int(round(len(samples) * dst_rate / src_rate)))
    out = []
    for i in range(out_len):
        src_pos = i * src_rate / dst_rate
        i0 = int(src_pos)
        i1 = min(i0 + 1, len(samples) - 1)
        frac = src_pos - i0
        v = samples[i0] * (1.0 - frac) + samples[i1] * frac
        out.append(v)
    return out


def to_s8(samples):
    out = []
    for v in samples:
        # clamp to signed 16 then scale if wide
        if isinstance(v, float):
            iv = int(round(v))
        else:
            iv = int(v)
        # if still in 16-bit range, shift down
        if iv > 127 or iv < -128:
            iv = iv // 256
        if iv > 127:
            iv = 127
        if iv < -128:
            iv = -128
        out.append(iv)
    return out


def emit_inc(name: str, rate: int, data: list[int]) -> str:
    # pad to 4-byte boundary for DMA word packing
    while len(data) % 4 != 0:
        data.append(0)
    lines = [
        f"{{ auto-generated by tools/voice.py — signed 8-bit PCM @ {rate} Hz }}",
        f"const Sample{name}Rate = {rate};",
        f"  Sample{name}Len  = {len(data)};",
        f"  Sample{name}Data: array[0..{len(data) - 1}] of ShortInt = (",
    ]
    row = []
    for i, b in enumerate(data):
        row.append(f"{b:4d}")
        if len(row) == 16 or i == len(data) - 1:
            sep = "," if i < len(data) - 1 else ""
            lines.append("    " + ", ".join(row) + sep)
            row = []
    lines.append("  );")
    lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("wav", type=Path)
    ap.add_argument("-o", "--out", type=Path, default=None)
    ap.add_argument("--name", default=None, help="Pascal stem (default: wav stem)")
    ap.add_argument("--rate", type=int, default=16384, help="output sample rate Hz")
    ap.add_argument("--gain", type=float, default=1.0, help="linear gain before clamp")
    args = ap.parse_args()

    src_rate, samples = read_wav(args.wav)
    if args.gain != 1.0:
        samples = [s * args.gain for s in samples]
    samples = resample(samples, src_rate, args.rate)
    data = to_s8(samples)

    stem = args.name or args.wav.stem
    # Pascal identifier stem: CapCase-ish
    name = "".join(p.capitalize() for p in stem.replace("-", "_").split("_"))
    if not name.isidentifier():
        raise SystemExit(f"bad sample name stem '{name}'")

    text = emit_inc(name, args.rate, data)
    out = args.out or args.wav.with_suffix(".inc")
    out.write_text(text, encoding="utf-8")
    dur = len(data) / args.rate
    print(f"OK: {out}  {len(data)} samples @ {args.rate} Hz (~{dur:.2f}s)  name=Sample{name}")


if __name__ == "__main__":
    main()
